Parameters:
  
  PlatformType:
    Type: String  
    Default: "64bit Amazon Linux 2 v3.5.3 running PHP 8.1"
    
  VPCID:
    Type: String
    #Default: vpc-08d7d400b2d32898e
  
  InstanceSubnets:
    Type: String
    
  ELBSubnets:
    Type: String
  
  AutoscalingGroupMin:
    Type: String
    Default: '1'
    
  AutoscalingGroupMax:
    Type: String
    Default: '2'

  InstanceTypes:
    Type: String
    Default: 't2.micro'

  InstanceSecurityGroups:
    Type: String
    
  SecretRDSARN:
    Type: String

  FileSystem:
    Type: String

  SSLCertificateArns:
    Type: String
    

################################################################
#                        RESOURCES                             #
################################################################
Resources:

#####################APPLICATION########################################
  Application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: Web app

#######################CONFIGURATION TEMPLATE#######################################  
 
  ConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref Application
      Description: Environmnet Configuration Template
      OptionSettings:
      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value: !Ref VPCID
        
      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: !Ref InstanceSubnets
        
      - Namespace: aws:ec2:vpc
        OptionName: ELBSubnets
        Value: !Ref ELBSubnets
        
      - Namespace: aws:ec2:vpc
        OptionName: ELBScheme
        Value: public

      - Namespace: aws:ec2:instances
        OptionName: InstanceTypes
        Value: !Ref InstanceTypes
        
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: !Ref AutoscalingGroupMin
        
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: !Ref AutoscalingGroupMax
        
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
        
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: LoadBalancerType
        Value: application  
        
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref InstanceProfile

      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: SecurityGroups
        Value: !Ref InstanceSecurityGroups
        
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: SecretRDSARN
        Value: !Ref SecretRDSARN

      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: FileSystem
        Value: !Ref FileSystem

      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: Region
        Value: !Ref "AWS::Region"    

      - Namespace: aws:elbv2:listener:443
        OptionName: Protocol
        Value: HTTPS  
 
      - Namespace: aws:elbv2:listener:443
        OptionName: SSLCertificateArns
        Value: !Ref SSLCertificateArns
        
      SolutionStackName: !Ref PlatformType    

##########################ENVIRONMENT############################  
  Environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref Application
      Description: Environment
      TemplateName: !Ref ConfigurationTemplate
      #SolutionStackName: !Ref PlatformType

####################IAM ROLES############################  
  InstanceRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Beanstalk EC2 role
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: AccessSecretRDSTEST
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'secretsmanager:GetSecretValue'
                Resource: !Ref SecretRDSARN 
  
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref InstanceRole

################################################################
#                        OUTPUT                                #
################################################################
Outputs:

  BeanstalkELB:
    Description: 'ELB DNS'  
    Value: !GetAtt Environment.EndpointURL

  BeanstalkID:
    Description: 'Resource id'  
    Value: !Ref Environment