Parameters:

####################NESTED STACK CF########################
  NetTier3AZ2STACKFILE:
    Type: String
    Default: https://worpress-matteo-mus.s3.eu-central-1.amazonaws.com/net-3tier-2az.yaml
    
####################NetTier3AZ2#####################
  CidrBlock28:
    Description: 'Specify the 2nd Octet of IPv4 CIDR block for the VPC (10.XXX.0.0/16) in the range [0-255]'
    Type: Number
    Default: 0
    ConstraintDescription: 'Must be in the range [0-255]'
    MinValue: 0
    MaxValue: 255

####################BEANSTALK###################
  PlatformType:
    Type: String  
    Default: "64bit Amazon Linux 2 v3.5.3 running PHP 8.1"
     
  AutoscalingGroupMin:
    Type: String
    Default: '1'
    
  AutoscalingGroupMax:
    Type: String
    Default: '2'

  InstanceTypes:
    Type: String
    Default: 't2.micro'

  SSLCertificateArns:
    Type: String
    Default: ""

    
######################RDS#############################

  DBUsername:
    Type: String
    Default: admin
  
  DBName:
    Type: String
    Default: ebdb
    
  DBEngine:
    Type: String
    Default: aurora-mysql
    
  DBEngineVersion:
    Type: String
    Default: 8.0.mysql_aurora.3.02.0  
       
  DBPort:
    Type: Number
    Default: 3306

  ServerlessMinCapacity:
    Type: Number
    Default: 0.5

  ServerlessMaxCapacity:
    Type: Number
    Default: 1    

#################################ROUTE53############################
  HostedZoneId:
    Type: String
    #Default: Z05815252IRTT0NENL5Q0
    Default: ""
    
  BeanstalkELBHostedZoneId:
    Type: String  
    #Default: Z1FRNW7UH4DEZJ 
    Default: ""
    
  Domain:
    Type: String
    #Default: matteomus.click
    Default: ""

  SubDomain:
    Type: String
    Default: ""
    
  EvaluateTargetHealth:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false

################################################################
#                        CONDITIONS                            #
################################################################
Conditions:
  
  HTTPSEnabled: !Not [!Equals [!Ref SSLCertificateArns, '']]
  HTTPSDisabled: !Equals [!Ref SSLCertificateArns, '']

################################################################
#                        RESOURCES                             #
################################################################
Resources:

####################NetTier3AZ2#####################  
  NetTier3AZ2STACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://worpress-matteo-mus.s3.eu-central-1.amazonaws.com/net-3tier-2az.yaml
      Parameters:
        CidrBlock28: !Ref CidrBlock28

####################BEANSTALK###################
  BeanstalkHTTPSTACK:
    Condition: HTTPSDisabled
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://worpress-matteo-mus.s3.eu-central-1.amazonaws.com/beanstalk.yaml
      Parameters:
        PlatformType: !Ref PlatformType
        VPCID: !GetAtt NetTier3AZ2STACK.Outputs.VPCID  
        InstanceSubnets: !GetAtt NetTier3AZ2STACK.Outputs.SubnetsPrivateEC2
        ELBSubnets: !GetAtt NetTier3AZ2STACK.Outputs.SubnetsPublic
        InstanceSecurityGroups: !Join [ ',', [ !GetAtt RDSSTACK.Outputs.EC2RDSSecurityGroup, !GetAtt EFSSTACK.Outputs.EC2EFSSecurityGroup ] ]
        SecretRDSARN: !GetAtt RDSSTACK.Outputs.AuroraMasterSecret
        FileSystem: !GetAtt EFSSTACK.Outputs.FileSystem


  BeanstalkHTTPSSTACK:
    Condition: HTTPSEnabled
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://worpress-matteo-mus.s3.eu-central-1.amazonaws.com/beanstalk_https.yaml
      Parameters:
        PlatformType: !Ref PlatformType
        VPCID: !GetAtt NetTier3AZ2STACK.Outputs.VPCID  
        InstanceSubnets: !GetAtt NetTier3AZ2STACK.Outputs.SubnetsPrivateEC2
        ELBSubnets: !GetAtt NetTier3AZ2STACK.Outputs.SubnetsPublic
        InstanceSecurityGroups: !Join [ ',', [ !GetAtt RDSSTACK.Outputs.EC2RDSSecurityGroup, !GetAtt EFSSTACK.Outputs.EC2EFSSecurityGroup ] ]
        SecretRDSARN: !GetAtt RDSSTACK.Outputs.AuroraMasterSecret
        FileSystem: !GetAtt EFSSTACK.Outputs.FileSystem  
        SSLCertificateArns: !Ref SSLCertificateArns      

###################RDS############################
  RDSSTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://worpress-matteo-mus.s3.eu-central-1.amazonaws.com/rds-aurora-serverless.yaml
      Parameters:
        VPCID: !GetAtt NetTier3AZ2STACK.Outputs.VPCID
        RDSSubnets: !GetAtt NetTier3AZ2STACK.Outputs.SubnetsPrivateRDS
        
###################EFS############################
  EFSSTACK:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://worpress-matteo-mus.s3.eu-central-1.amazonaws.com/efs.yaml
      Parameters:
        VPCID: !GetAtt NetTier3AZ2STACK.Outputs.VPCID 
        SubnetsEC2: !GetAtt NetTier3AZ2STACK.Outputs.SubnetsPrivateEC2 

####################ROUTE53#########################
  ROUTE53HTTPSTACK:
    Condition: HTTPSDisabled
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://worpress-matteo-mus.s3.eu-central-1.amazonaws.com/route53.yaml
      Parameters:
        BeanstalkELB: !GetAtt BeanstalkHTTPSTACK.Outputs.BeanstalkELB
        HostedZoneId: !Ref HostedZoneId
        BeanstalkELBHostedZoneId: !Ref BeanstalkELBHostedZoneId
        Domain: !Ref Domain
        SubDomain: !Ref SubDomain    
        EvaluateTargetHealth: !Ref EvaluateTargetHealth

  ROUTE53HTTPSSTACK:
    Condition: HTTPSEnabled
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://worpress-matteo-mus.s3.eu-central-1.amazonaws.com/route53.yaml
      Parameters:
        BeanstalkELB: !GetAtt BeanstalkHTTPSSTACK.Outputs.BeanstalkELB
        HostedZoneId: !Ref HostedZoneId
        BeanstalkELBHostedZoneId: !Ref BeanstalkELBHostedZoneId
        Domain: !Ref Domain
        SubDomain: !Ref SubDomain    
        EvaluateTargetHealth: !Ref EvaluateTargetHealth              
        
        