Parameters:
    
  HostedZoneId:
    Type: String
    #Default: Z0633616EJKZKL17EKP7
    Default: ""
    
  BeanstalkELBHostedZoneId:
    Type: String  
    Default: ""
    
  Domain:
    Type: String
    Default: ""

  SubDomain:
    Type: String
    Default: ""

  BeanstalkELB:
    Type: String
    
  EvaluateTargetHealth:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false

################################################################
#                        CONDITIONS                            #
################################################################
Conditions:
  
  CreateDNSRecordDomain: !And
    - !Not [!Equals [!Ref HostedZoneId, '']]
    - !Not [!Equals [!Ref BeanstalkELBHostedZoneId, '']]
    - !Not [!Equals [!Ref Domain, '']]
    - !Equals [!Ref SubDomain, '']

  CreateDNSRecordSubDomain: !And
    - !Not [!Equals [!Ref HostedZoneId, '']]
    - !Not [!Equals [!Ref BeanstalkELBHostedZoneId, '']]
    - !Not [!Equals [!Ref Domain, '']]
    - !Not [!Equals [!Ref SubDomain, '']]  

################################################################
#                        RESOURCES                             #
################################################################
Resources:     

  DNSRecordDomain:
    Condition: CreateDNSRecordDomain
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Ref Domain
          Type: A
          AliasTarget:
            HostedZoneId: !Ref BeanstalkELBHostedZoneId
            DNSName: !Ref BeanstalkELB
            EvaluateTargetHealth: !Ref EvaluateTargetHealth

  DNSRecordSubDomain:
    Condition: CreateDNSRecordSubDomain
    Type: 'AWS::Route53::RecordSetGroup'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Join [".",[!Ref SubDomain, !Ref Domain]]
          Type: A
          AliasTarget:
            HostedZoneId: !Ref BeanstalkELBHostedZoneId
            DNSName: !Ref BeanstalkELB
            EvaluateTargetHealth: !Ref EvaluateTargetHealth          
           