Parameters:

  Domain:
    Type: String
    Default: matteomus.click

Resources:
  InternalRootCA:
    Type: 'AWS::ACMPCA::CertificateAuthority'
    Properties:
      Type: ROOT
      KeyAlgorithm: RSA_2048
      SigningAlgorithm: SHA256WITHRSA
      Subject:
        Country: IT
        State: AO
        Locality: AO
        Organization: MyOrganization
        OrganizationalUnit: MyOrganizationalUnit
        CommonName: My own Root CA
        SerialNumber: '12345678'
      RevocationConfiguration:
        CrlConfiguration:
          Enabled: false

  InternalRootCACertificate:
    Type: 'AWS::ACMPCA::Certificate'
    Properties:
      CertificateAuthorityArn: !Ref InternalRootCA
      CertificateSigningRequest: !GetAtt
        - InternalRootCA
        - CertificateSigningRequest
      SigningAlgorithm: SHA256WITHRSA
      TemplateArn: 'arn:aws:acm-pca:::template/RootCACertificate/V1'
      Validity:
        Type: YEARS
        Value: 1
  
  InternalRootCAActivation:
    Type: 'AWS::ACMPCA::CertificateAuthorityActivation'
    Properties:
      CertificateAuthorityArn: !Ref InternalRootCA
      Certificate: !GetAtt
        - InternalRootCACertificate
        - Certificate
      Status: ACTIVE
      
  ACMInternalCertificate:
    DependsOn: InternalRootCAActivation
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateAuthorityArn: !Ref InternalRootCA
      DomainName: !Ref Domain
      SubjectAlternativeNames: [!Join ["", ["*.", !Ref Domain]]]
            